version: "3.8"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cfautobooks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ocr-service:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.10
    container_name: ocr-service
    volumes:
      - ./backend/../Step1_OCR_Service:/ocr-service
    working_dir: /ocr-service
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8001:8000"

  api:
    build:
      context: ./backend
    container_name: cfautobooks-api
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/config/.env
    depends_on:
      - db
      - ocr-service
    ports:
      - "8000:8000"

  frontend:
    image: nginx:alpine
    container_name: cfautobooks-frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  postgres_data: