# render.yaml

services:
  - type: web
    name: cfautobooks-frontend
    env: static
    branch: main
    repo: https://github.com/CFautobooks/CFautobooks-demo.git
    staticPublishPath: frontend

  - type: web
    name: cfautobooks-api
    env: docker
    branch: main
    repo: https://github.com/CFautobooks/CFautobooks-demo.git
    dockerfilePath: backend/Dockerfile
    plan: free

  - type: web
    name: cfautobooks-ocr
    env: docker
    branch: main
    repo: https://github.com/CFautobooks/CFautobooks-demo.git
    dockerfilePath: Step1_OCR_Service/Dockerfile
    plan: free

databases:
  - name: cfautobooks-db
    plan: free
    databaseName: cfautobooks
