# render.yaml

services:
  - type: web
    name: cfautobooks-frontend
    env: static
    repo: https://github.com/CFautobooks/CFautobooks-demo.git
    branch: main
    staticPublishPath: frontend

  - type: web
    name: cfautobooks-api
    env: docker
    repo: https://github.com/CFautobooks/CFautobooks-demo.git
    branch: main
    dockerfilePath: backend/Dockerfile

  - type: web
    name: cfautobooks-ocr
    env: docker
    repo: https://github.com/CFautobooks/CFautobooks-demo.git
    branch: main
    dockerfilePath: Step1_OCR_Service/Dockerfile

databases:
  - name: cfautobooks-db
    plan: free
    databaseName: cfautobooks

