services:
  - type: web
    name: horse-racing-api
    env: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    plan: free

  - type: web
    name: horse-racing-frontend
    env: docker
    rootDir: frontend
    dockerfilePath: Dockerfile
    plan: free

databases:
  - name: horse-racing-db
    plan: free
    databaseName: horseracing
