# render.yaml
services:
  - type: web
    name: cfautobooks-api
    env: docker
    branch: main
    repo: https://github.com/CFautobooks/CFautobooks-demo.git

    # tell Render to chdir into `backend/` before building
    rootDir: backend

    # DockerfilePath is now relative to backend/
    dockerfilePath: Dockerfile

    plan: free

