version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cfautobooks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ocr-service:
    build:
      context: ./Step1_OCR_Service
      dockerfile: Dockerfile
    container_name: ocr-service
    ports:
      - "8001:8000"

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cfautobooks-api
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - ocr-service
    ports:
      - "8000:8000"

volumes:
  postgres_data:
